export const Languages = [
  { id: 1, value: "Hindi", details: "Official language of India; widely spoken across northern and central India; Devanagari script" },
  { id: 2, value: "Bengali", details: "Official language of West Bengal and Tripura; second most spoken language in India; Bengali script" },
  { id: 3, value: "Telugu", details: "Official language of Andhra Pradesh and Telangana; Telugu script" },
  { id: 4, value: "Marathi", details: "Official language of Maharashtra; Devanagari script" },
  { id: 5, value: "Tamil", details: "Official language of Tamil Nadu and Puducherry; Tamil script" },
  { id: 6, value: "Urdu", details: "Official language in several states; widely used in northern India; Perso-Arabic script" },
  { id: 7, value: "Gujarati", details: "Official language of Gujarat; Gujarati script" },
  { id: 8, value: "Kannada", details: "Official language of Karnataka; Kannada script" },
  { id: 9, value: "Odia", details: "Official language of Odisha; Odia script" },
  { id: 10, value: "Malayalam", details: "Official language of Kerala and Lakshadweep; Malayalam script" },
  { id: 11, value: "Punjabi", details: "Official language of Punjab; Gurmukhi script" },
  { id: 12, value: "Assamese", details: "Official language of Assam; Assamese script" },
  { id: 13, value: "Maithili", details: "Recognized language in Bihar and Jharkhand; Devanagari script" },
  { id: 14, value: "Santali", details: "Recognized language in Jharkhand, Odisha, West Bengal; Ol Chiki script" },
  { id: 15, value: "Kashmiri", details: "Official language of Jammu & Kashmir; Perso-Arabic script" },
  { id: 16, value: "Sanskrit", details: "Ancient language of India; used in classical literature and rituals; Devanagari script" },
  { id: 17, value: "Dogri", details: "Official language in Jammu & Kashmir; Devanagari script" },
  { id: 18, value: "Manipuri (Meitei)", details: "Official language of Manipur; Meitei Mayek script" },
  { id: 19, value: "Bodo", details: "Official language in Assam; Devanagari script" },
  { id: 20, value: "Nepali", details: "Official language in Sikkim and some parts of North Bengal; Devanagari script" },
  { id: 21, value: "Sindhi", details: "Recognized language in India; Perso-Arabic and Devanagari scripts" },
  { id: 22, value: "Konkani", details: "Official language of Goa; Devanagari script" }
];
